# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4229873017f088547f6d9ffbc76ae3abc7cc8c17c73316ab9fa214f22132bd5c1d1c02ec10a6e05758f06fb5fefa8055538e3ac7de59b057a4f97ae939c63544

test:
  secret_key_base: df9caa1bcbaa04568239e6580eee99c5d0fb4ff0123e8c54e5981976c9d0d6ed436ad2a122af580a3588007605f9fdd897b8e1b63cd8ff8146e635f6afad8849

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
